### ISSUE TITLE
[FRONT] Répartition des taches

### ISSUE THREAD

**Issue by heticeric** [Paulehair/SSDP-G2#81]
@ynohtn @SoleauSimon @marion-ott 
Merci de me préciser les rôles de chacun.
https://github.com/Paulehair/SSDP-G2/graphs/contributors laisse apparaître une grosse différence de travail.
Pourquoi ?

**Comment by marion-ott** [comment]
Anthony : dev front
Simon : dev front
Marion : dev back/front
Nous avons travaillé tous les trois sur le découpage des composants, l'architecture et l'intégration.
Anthony a travaillé sur la logique et l'implémentation des hooks (natifs et custom), quant à Simon il a aussi géré le Storybook qu'aucun de nous ne connaissait, il faut donc prendre en compte le temps de recherche et de documentation. Quant à moi j'ai principalement travaillé sur la liaison avec l'API et l'affichage des données.

**Comment by heticeric** [comment]
Merci pour ces éclaircissements
Beau travail en tous cas
